# Generated by Django 6.0.6 on 2026-09-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_purchaseorder_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase (Stock In)'), ('usage', 'Usage (Stock Out)'), ('adjustment', 'Manual Adjustment'), ('spoilage', 'Spoilage / Waste'), ('return', 'Return to Supplier'), ('transfer', 'Transfer'), ('reversal', 'Reversal — Cancelled Order / Removed Item')], max_length=20),
        ),
    ]
