# Generated by Django 6.0.6 on 2026-09-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Stock In — Purchase / Delivery'), ('usage', 'Stock Out — Used in Orders (automatic)'), ('adjustment', 'Stock Out — Manual Adjustment'), ('spoilage', 'Stock Out — Spoilage / Waste'), ('return', 'Stock Out — Return to Supplier'), ('transfer', 'Stock In — Transfer'), ('reversal', 'Stock In — Order Cancelled (automatic)')], max_length=20),
        ),
    ]
