# Generated by Django 6.0.6 on 2026-09-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement_type_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='emailed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
