# Generated by Django 6.0.6 on 2026-09-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_purchaseorder_emailed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['name'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='inventory_i_categor_ed3703_idx',
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['name'], name='inventory_i_name_43f130_idx'),
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='category',
        ),
        migrations.DeleteModel(
            name='InventoryCategory',
        ),
    ]
