# Generated by Django 6.0.6 on 2026-09-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference',
            field=models.CharField(help_text="Numbered automatically from the order's own id, e.g. PO-000042.", max_length=100, unique=True, verbose_name='PO number'),
        ),
    ]
