# Generated by Django 6.0.6 on 2026-09-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_supplier_website_alter_supplier_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='social',
            field=models.CharField(blank=True, help_text="The supplier's social account (fb, ig, tiktok)"),
        ),
    ]
