# Generated by Django 6.0.6 on 2026-09-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_supplier_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='social',
            field=models.URLField(blank=True, help_text="The supplier's social account (fb, ig, tiktok)"),
        ),
    ]
