# Generated by Django 6.0.6 on 2026-09-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_supplier_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(help_text="Can be written in a different metric unit than the inventory item itself (e.g. ml for an item tracked in L) — it's converted automatically.", max_length=20),
        ),
    ]
