"""
Django settings for caffeine_corner project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
from django.templatetags.static import static
from django.urls import reverse_lazy
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# NOTE: ALLOWED_HOSTS is set once, further down (near CSRF_TRUSTED_ORIGINS),
# with the actual list of hosts this runs on (127.0.0.1, LAN IPs, etc.) —
# it used to be redefined here too as an empty list, which happened to be
# harmless only because Python re-assignment let the later one win, but it
# was confusing and one edit away from silently locking every host out.


# Application definition

INSTALLED_APPS = [
    # Unfold - MUST be before django.contrib.admin
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',

    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',

    # Auth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'dj_rest_auth',
    'dj_rest_auth.registration',

    # REST
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',

    # CORS
    'corsheaders',

    # Your apps
    'online_shop',
    'authentication',
    'inventory',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'caffeine_corner.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'caffeine_corner.context_processors.unfold_admin_theme',
            ],
        },
    },
]

WSGI_APPLICATION = 'caffeine_corner.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# Without this, dj_rest_auth's SocialLoginView (GoogleLoginView/FacebookLoginView)
# defaults to its own DRF Token auth and replies with {"key": "..."} instead of
# {"access": ..., "refresh": ...} — the frontend then stores `undefined` for both
# tokens, so it looks like Google sign-in "succeeds" but every request after that
# 401s and the user gets bounced back out. USE_JWT makes it issue SimpleJWT tokens
# (same kind the rest of the app already uses) in the response body; HTTPONLY is
# off because the frontend keeps tokens in localStorage, not cookies.
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False,
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'

SOCIALACCOUNT_AUTO_SIGNUP = True
# Gawin itong ganito
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
    }
}
SITE_ID = 2
EMAIL_BACKEND = 'authentication.email_backend.UnverifiedSSLEmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

AUTH_USER_MODEL = 'authentication.User'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.6', '192.168.1.8']

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://192.168.1.6:5173',
    'http://192.168.1.8:5173',
]

# Where /admin/login/ sends you when the URL has no ?next= (Unfold's login
# form has no hidden "next" field, so a direct visit — after logging out, or
# from a bookmark — used to land on Django's default /accounts/profile/,
# which doesn't exist here: a 404 right after a successful login).
LOGIN_REDIRECT_URL = 'admin:index'

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_ALL_ORIGINS = True

FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://192.168.1.8:5173')

# Free key from https://cloud.maptiler.com/account/keys/ — used by the Town
# Zone admin map for the full detailed OSM-style basemap. Left blank, the
# map falls back to Esri's (less detailed but key-free) street tiles.
MAPTILER_KEY = os.getenv('MAPTILER_KEY', '')

UNFOLD = {
    "SITE_TITLE": "CAFFIENE CORNER",
    "SITE_HEADER": "CAFFIENE CORNER",
    "SITE_URL": "/",
    "SITE_ICON": lambda request: static("img/Logo.jpg"),
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "DASHBOARD_CALLBACK": "inventory.views.dashboard_callback",
    "LOGIN": {
        "image": lambda request: static("img/Background.jpeg"),
    },
    "STYLES": [
        # Same Google Font as the React frontend's brand wordmark (see
        # frontend/index.html) — keeps "CAFFIENE CORNER" in the sidebar
        # looking like the one customers see, not the admin's default Inter.
        lambda request: "https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,600;0,700;1,400&display=swap",
        lambda request: static("css/admin-theme.css"),
    ],
    # Unfold already loads HTMX itself (unfold/js/htmx/htmx.js) on every
    # admin page — this just teaches it to send Django's CSRF token, used
    # by the inline status/payment toggles on the Orders list (see
    # OrderAdmin.show_status / show_payment_status).
    "SCRIPTS": [
        lambda request: static("js/htmx-csrf.js"),
        lambda request: static("js/notif-badge.js"),
        lambda request: static("js/orderitem-price.js"),
    ],
    "COLORS": {
        "primary": {
            "50":  "254 249 245",
            "100": "252 240 230",
            "200": "249 220 195",
            "300": "244 190 145",
            "400": "236 152 85",
            "500": "196 128 65",
            "600": "160 100 45",
            "700": "120 72 28",
            "800": "85 48 16",
            "900": "55 28 5",
            "950": "35 16 2",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Store",
                "separator": False,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Orders",
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:online_shop_order_changelist"),
                    },
                    {
                        "title": "Sales Report",
                        "icon": "bar_chart",
                        "link": "/admin/sales-report/",
                    },
                    {
                        "title": "Notifications",
                        "icon": "notifications",
                        "link": reverse_lazy("admin:online_shop_notification_changelist"),
                        # Optional: show unread count badge
                    },
                    {
                        "title": "Town Zones",
                        "icon": "location_on",
                        "link": reverse_lazy("admin:online_shop_townzone_changelist"),
                    }
                ],
            },
            {
                "title": "Products",
                "separator": True,
                "items": [
                    {
                        "title": "Products",
                        "icon": "local_cafe",
                        "link": reverse_lazy("admin:online_shop_product_changelist"),
                    },
                    {
                        "title": "Categories",
                        "icon": "category",
                        "link": reverse_lazy("admin:online_shop_category_changelist"),
                    },
                    {
                        "title": "Ratings",
                        "icon": "star",
                        "link": reverse_lazy("admin:online_shop_rating_changelist"),
                    },
                    {
                        "title": "Loyalty Points",
                        "icon": "loyalty",
                        "link": reverse_lazy("admin:online_shop_loyaltypoint_changelist"),
                    },
                ],
            },
            {
                "title": "Inventory",
                "separator": True,
                "items": [
                    {
                        "title": "Inventory Items",
                        "icon": "inventory",
                        "link": reverse_lazy("admin:inventory_inventory_changelist"),
                    },
                    {
                        "title": "Purchase Orders",
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:inventory_purchaseorder_changelist"),
                    },
                    {
                        "title": "Suppliers",
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:inventory_supplier_changelist"),
                    },
                    {
                        "title": "Inv. Categories",
                        "icon": "folder",
                        "link": reverse_lazy("admin:inventory_inventorycategory_changelist"),
                    },
                ],
            },
            {
                "title": "Users & Access",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": reverse_lazy("admin:authentication_user_changelist"),
                    },
                    {
                        "title": "OTP Codes",
                        "icon": "lock",
                        "link": reverse_lazy("admin:authentication_otpcode_changelist"),
                    },
                    {
                        "title": "Activity Logs",      # ← dagdag
                        "icon": "history",
                        "link": reverse_lazy("admin:online_shop_activitylog_changelist"),
                    },
                    {
                        "title": "Dine-in QR Codes",
                        "icon": "qr_code",
                        "link": "/admin/table-qr/",  # ← isang link lang sa page
                    },
                ],
            },
        ],
    },
}