# Generated by Django 6.0.6 on 2026-09-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_rider',
            field=models.BooleanField(default=False, help_text='Check kung delivery rider ang account na ito'),
        ),
    ]
