# Generated by Django 6.0.5 on 2026-05-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0002_alter_variant_barcode_alter_variant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='downpayment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='event_date',
            field=models.DateField(blank=True, help_text='Para sa bulk/catering orders', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('bulk', 'Bulk / Catering')], default='regular', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='pax',
            field=models.PositiveIntegerField(default=0, help_text='Number of persons'),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('downpayment', 'Downpayment Paid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='unpaid', max_length=15),
        ),
    ]
