# Generated by Django 6.0.6 on 2026-07-27 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0006_order_table_number_alter_order_order_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TownZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck para hindi pa muna ma-deliver dito')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order para dito maka-order', max_digits=10)),
                ('estimated_time', models.CharField(blank=True, help_text="e.g. '30-45 mins'", max_length=50)),
            ],
            options={
                'verbose_name': 'Town Zone',
                'verbose_name_plural': 'Town Zones',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Delivery zone — regular at bulk orders lang', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='online_shop.townzone'),
        ),
    ]
