# Generated by Django 6.0.6 on 2026-07-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0007_townzone_order_delivery_fee_order_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=8, help_text='Philippine mobile number, e.g. 09171234567', max_length=15),
            preserve_default=False,
        ),
    ]
