# Generated by Django 6.0.6 on 2026-09-01 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0008_order_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_rider',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_rider': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_proofs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
