# Generated by Django 6.0.6 on 2026-09-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0010_alter_order_order_type_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('dine_in', 'Dine-in'), ('pickup', 'Pick-up')], default='regular', max_length=10),
        ),
    ]
