# Generated by Django 6.0.6 on 2026-09-06 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0011_alter_order_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='townzone',
            name='min_order_amount',
        ),
    ]
