# Generated by Django 6.0.6 on 2026-09-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0013_order_delivery_latitude_order_delivery_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='townzone',
            name='center_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Approximate center ng zone para sa map auto-pan', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='townzone',
            name='center_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
