# Generated by Django 6.0.6 on 2026-09-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0014_townzone_center_latitude_townzone_center_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('regular', 'Delivery'), ('dine_in', 'Dine-in'), ('pickup', 'Pick-up')], default='regular', max_length=10),
        ),
    ]
