# Generated by Django 6.0.6 on 2026-09-22 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0015_order_type_delivery_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remitted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittances_received', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(limit_choices_to={'is_rider': True}, on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remittance',
                'verbose_name_plural': 'Remittances',
                'ordering': ('-remitted_at',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='remittance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='online_shop.remittance'),
        ),
    ]
