# Generated by Django 6.0.6 on 2026-09-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0016_remittance_order_remittance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_rider_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
