# Generated by Django 6.0.6 on 2026-09-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0017_order_assigned_rider_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time_production',
            field=models.IntegerField(default=0),
        ),
    ]
