# Generated by Django 6.0.6 on 2026-09-23 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0018_product_time_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_production',
            field=models.IntegerField(default=0, help_text='How long this item takes to make (pastries usually longer than drinks). Used to estimate ready/delivery time and how long a rider stays tied up on an order. Leave at 0 if unsure — a sensible minimum is still assumed.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preparation time (minutes)'),
        ),
    ]
